# Generated by Django 4.1.4 on 2022-12-29 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apex", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("duration", models.CharField(max_length=50)),
                ("features", models.CharField(blank=True, max_length=300, null=True)),
                ("price_for_gen", models.IntegerField(blank=True, null=True)),
                ("price_for_sc", models.IntegerField(blank=True, null=True)),
                ("price_for_st", models.IntegerField(blank=True, null=True)),
                ("price_for_obc", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("name", models.CharField(max_length=200)),
                ("father_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "mobile_nnumber",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GEN", "General"),
                            ("SC", "SC"),
                            ("ST", "ST"),
                            ("OBC", "OBC"),
                            ("OTH", "OTHER"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "certificate_status",
                    models.CharField(
                        choices=[
                            ("RECIEVED", "RECEIVED"),
                            ("READY", "READY"),
                            ("IN_PROGRESS", "IN PROGRESS"),
                            ("NOT_INITIATED", "NOT INITAIATED"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apex.course"
                    ),
                ),
            ],
        ),
    ]
