# Generated by Django 4.1.4 on 2022-12-29 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apex", "0002_course_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment", models.IntegerField()),
                (
                    "proof",
                    models.FileField(
                        blank=True, null=True, upload_to="fee_proofs/%Y/%m"
                    ),
                ),
                ("is_new", models.BooleanField()),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apex.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apex.student",
                    ),
                ),
            ],
        ),
    ]
